# Generated by Django 6.1.1 on 2026-10-06 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('current_allocated_space', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
